version: "3.9"
services:
  db:
    image: mysql:8.4.0
    container_name: mysql-container
    restart: always
    ports:
      - "13306:3306"
    env_file:
      - .env
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD"
      # ヘルスチェックのインターバルは10秒
      interval: 10s
      # タイムアウト時間は10秒
      timeout: 10s
      # リトライ回数は3回
      retries: 3
      # ヘルスチェックが失敗しても無視する時間は60秒
      start_period: 60s

  web:
    build: .
    container_name: django-container
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: sh /app/entrypoint.sh
